In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('./data/lena.jpg')

print('img.ndim = ', img.ndim)
print('img.shpae = ', img.shape)
print('img.dtype = ', img.dtype)

img = img.astype(np.int32)
print('img.dtype = ', img.dtype)

img = np.uint8(img)
print('img.dtype = ', img.dtype)

img.ndim =  3
img.shpae =  (512, 512, 3)
img.dtype =  uint8
img.dtype =  int32
img.dtype =  uint8


In [3]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
print('img.shape = ', img.shape)

img = img.flatten()
print('img.shape = ', img.shape)

img = img.reshape(512, 512)
print('img.shape = ', img.shape)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

img.shape =  (512, 512)
img.shape =  (262144,)
img.shape =  (512, 512)


In [5]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

img[100, 200] = 50
print(img[100:110, 200:210])

[[ 50 143 145 132 147 144 142 139 132 138]
 [138 138 143 151 137 144 139 139 138 138]
 [132 139 153 140 133 136 143 138 137 128]
 [137 146 138 125 132 145 139 142 130 128]
 [149 139 130 137 140 145 136 133 132 141]
 [141 139 134 149 149 137 132 127 140 140]
 [142 148 139 142 144 138 146 135 131 130]
 [151 146 136 131 142 144 149 135 126 132]
 [147 131 135 138 147 139 128 125 134 138]
 [135 132 149 142 134 128 122 135 138 129]]


In [6]:
img[100:400, 200:300] = 0

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
img = cv2.imread('./data/lena.jpg')
img[100, 200] = [255, 0, 0] #ㅋ라라
print(img[100, 200:210])

[[255   0   0]
 [116 115 207]
 [120 116 211]
 [107 103 198]
 [119 121 209]
 [116 118 206]
 [115 114 206]
 [112 111 203]
 [104 105 195]
 [110 112 200]]


In [8]:
img[100:400, 200:300] = [255, 0, 0]

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
img = cv2.imread('./data/lena.jpg')

img[100:400, 200:300, 0] = 255
img[100:400, 300:400, 1] = 255
img[100:400, 400:500, 2] = 255

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()