In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

(h, w) = img.shape
print(h, w)

(cy, cx) = (h//2, w//2)
print(cy, cx)

roi = img[0:cy, 0:cx]

cv2.imshow('img', img)
cv2.imshow('ROI', roi)
cv2.waitKey()
cv2.destroyAllWindows()

512 512
256 256


In [8]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape, dtype = src.dtype)

N = 64
height, width = src.shape

h = height // N
w = width // N

for i in range(N):
    for j in range(N):
        y = i*h
        x = j*w
        roi = src[y:y+h, x:x+w]
        val = cv2.mean(roi)
        
        dst[y:y+h, x:x+w] = val[0]
        
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
roi = cv2.selectROI(src)
print('roi = ', roi)

image = src[roi[1]:roi[1]+roi[3], roi[0]:roi[0]+roi[2]]

cv2.imshow('img', image)
cv2.waitKey()
cv2.destroyAllWindows()

roi =  (98, 75, 362, 364)


In [15]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
rects = cv2.selectROIs('src', src, False, False)
print('rects = ', rects)

for r in rects:
    cv2.rectangle(src, (r[0], r[1]), (r[0] + r[2], r[1] + r[3]), 255)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

rects =  [[212  16 134 167]
 [184 256 123 142]
 [332 241  98 125]
 [207 137 127 181]
 [ 57 112 145 156]
 [299 174 205 285]
 [299 174 205 285]
 [173 124 123 118]
 [234 158 195 291]
 [196 184 148 210]
 [209 225 176 229]
 [209 181 208 215]
 [236 224 134 158]]
