In [2]:
import cv2
import numpy as np

In [3]:
src = cv2.imread('./data/circles.jpg') #뒤에 암것도 안 쓰면 칼라든 그레이든 무조건 칼라로 읽음
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

#오브젝트가 까만색이니 반전함
ret, res = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY_INV) #이진값으로 바꿔줌, 맥스 255, 옵션 : 128보다 큰 애는 0, 작은 애는 255(인버스라서)

cv2.imshow('src', src)
cv2.imshow('res', res)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
ret, labels, stats, centroids = cv2.connectedComponentsWithStats(res) #레이블링 함수 (두종류(withstats 없는 거, 있는 거))
#labels : 라벨이 들어간 이미지 반환
print('ret = ', ret) #나머지 하나 : 백그라운드
print('stats = ', stats) #바운딩박스 정보
print('centroids = ', centroids) #각 컴포넌트의 중점

ret =  4
stats =  [[     0      0    512    512 222719]
 [   308     86    125    125  12281]
 [   153    145    152    152  18152]
 [   292    338    107    107   8992]]
centroids =  [[247.77339607 258.80937863]
 [370.         148.        ]
 [228.5        220.50534376]
 [345.00077847 390.99477313]]


In [6]:
#라벨 디스플레이 코드(제대로 레이블링이 됐는지)
dst = np.zeros(src.shape, dtype = src.dtype)
for i in range(1, int(ret)):
    r = np.random.randint(256)
    g = np.random.randint(256)
    b = np.random.randint(256)
    dst[labels == i] = [b, g, r] #각 라벨 숫자마다 랜덤 색깔 지정

In [12]:
for i in range(1, int(ret)):
    x, y, w, h, a = stats[i]
    cv2.rectangle(dst, (x, y), (x + w, y + h), (0, 0, 255), 2) #컴포넌트별로 바운딩박스 그림
    cx, cy = centroids[i]
    cv2.circle(dst, (int(cx), int(cy)), 5, (255,0,0), -1)
    
    cv2.imshow('src', src)
    cv2.imshow('dst', dst)
    cv2.waitKey()
    cv2.destroyAllWindows()